added homework for 4.Functions
AlinaDashko/aqa-advanced-1 pull request #4
Opened 2023-09-13 20:53 UTC by AlinaDashko

2023-09-14 08:15 UTC, sttaran requested changes

2023-09-14 08:15 UTC, sttaran commented on functions/task2.js
> +function validate(age) {
name `validate` does not show that this function should return boolean value. Use another name like `calculateIsAdult`, `getIsAdult` etc

2023-09-14 08:15 UTC, sttaran commented on functions/task2.js
> +        console.log("True");
we should return boolean value but not print it

Якщо age відповідає умові, поверніть true, інакше поверніть false.

2023-09-14 08:15 UTC, sttaran commented on functions/task3.js
> +        countdown(num - 1);
function should not be called when num equals 0
Фунція повинна викликатися, доки num не стане менше або рівне 0.

2023-09-15 20:17 UTC, sttaran requested changes

2023-09-15 20:17 UTC, sttaran commented on functions/task2.js
> +    if (age >= 18) {
everything is correct from syntax perspective but you can make it easier 
just
```js
return age >= 18
```

2023-09-15 20:17 UTC, sttaran commented on functions/task3.js
> +        countdown(num - 1);
```js
function countdown(num) {
    console.log(num);
    if (num > 1) {
        countdown(num - 1);
    }
}
countdown(5);
```

2023-09-15 20:22 UTC, AlinaDashko commented on functions/task3.js
> +        countdown(num - 1);
Oh, thanks, I got it!

2023-09-15 20:42 UTC, sttaran approved these changes

2023-09-15 20:55 UTC, merged